###Rest API Client

### Get one
GET http://127.0.0.1:5000/cocktails/id/1005

### get All
GET http://127.0.0.1:5000/Cocktails/

### Insert a cocktail
POST http://127.0.0.1:5000/Cocktails 
Content-Type: application/json

{    
   
    "name": "201 or 200",
    "price": 15.25,
    "rating": 4.2,
    "ImagePath": ""
}
