###Rest API Client

### Get one
GET http://127.0.0.1:5000/cocktails/id/1012

### get All
GET http://127.0.0.1:5000/Cocktails/

### Insert a cocktail
POST http://127.0.0.1:5000/Cocktails 
Content-Type: application/json

{       
    "name": "ddl revised packages",
    "price": 15.25,
    "rating": 4.2,
    "ImagePath": "NoImage.jpg"
}

### Update a cocktail
PUT  http://127.0.0.1:5000/Cocktails 
Content-Type: application/json

{       
    "id": 1013,
    "name": "TWO revised packages",
    "price": 15.25,
    "rating": 4.2,
    "ImagePath": "NoImage.jpg"
}