name: BPD FrontEnd

on:    
  push:
    branches: main
    paths:
    - 'frontend/**'

#   pull_request:    
#     branches: main
#     paths:
#     - 'frontend/**'
#     types: [closed]
    
    
  workflow_dispatch:  

jobs:
  Build-Publish-Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore, Build, Test, Publish  
      run: |
        cd frontend
        dotnet restore   
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp 
    
    - name: Deploy App to Azure WebService
      uses: Azure/webapps-deploy@v2.2.5
      with:
        # Name of the Azure Web App
        app-name: 'FrontendCocktails/prod2'
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        #publish-profile: API_WEBAPP_PUBLISH_PROFILE
        #publish-profile: ${{ secrets.API_WEBAPP_PUBLISH_PROFILE }}   
        publish-profile: ${{ secrets.COCKTAIL_FRONTEND_PROD2_PUBLISH_PROFILE }}   
        #COCKTAIL_API_API_FRONTEND_PUBLISH_PROFILE
        # Enter an existing Slot other than the Production slot
        slot-name: prod2
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: ${{env.DOTNET_ROOT}}/myapp 
        
        
        
        
        
